name: Intro - Manual Workflow2

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/intro-manual-workflow2.yml'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: How's GitHub Actions?
        run: echo "Awesome!!"
